services:
  backend:
    build: ./memory-backend
    container_name: memory-backend
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=YourSessionSecretHere
      - SERVER_HOST=${SERVER_HOST}
    networks:
      - traefik-network
    restart: unless-stopped

  frontend:
    build:
      context: ./memory-frontend
      args:
        - VITE_API_URL=${BACKEND_API_URL}
        - VITE_SOCKET_URL=${BACKEND_SOCKET_URL}
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - traefik-network
    restart: unless-stopped

network:
  traefik-network:
    external: true
